library(testthat)
library(sqlr.mcycle)

test_check("sqlr.mcycle")

# # For development use only (comment the code after use (Ctrl + Shift + C))
#
# .rs.restartR()
# devtools::install()
# devtools::document()
# devtools:test()
# devtools::check()
# covr::package_coverage()
# covr::codecov(token = "")
# pkgdown::build_site(preview = TRUE)
# pkgdown::build_favicons(overwrite = TRUE)
# pkgdown::build_article("mctq")
# pkgdown::build_reference(preview = FALSE)
# codemetar::write_codemeta()
# codemetar::give_opinions()
# urlchecker::url_check()
# goodpractice::gp()
# spelling::spell_check_package()
# spelling::update_wordlist()
# usethis::use_tidy_description()
# usethis::use_coverage()
# usethis::use_pkgdown_github_pages()
# usethis::use_github_action_check_full()
# usethis::use_github_action_check_standard()
# usethis::use_logo("./.archive/ai/hex-logo.png")
# normalizePath(readClipboard(), "/", mustWork = FALSE)

# SQLR System
#
# sqlr::write_metadata("1ZKCBn3emTds8koqZ08QTeCtG8MGVK1Z-xgzTo4BDHI4")
# sqlr::write_sheet()
# devtools::document()
# .rs.restartR()
# devtools::install()
#
# sqlr::normalize_extdata()
# devtools::load_all(".")
# sqlr::build_reference()
# sqlr::write_trial()
# nrow(dplyr::filter(reference, criteria_id == "DUP")) +
# sqlr::sheet_nrow("trial_nr1") == nrow(reference)
